CREATE DATABASE IF NOT EXISTS `atlas` /*!40100 COLLATE 'utf8mb4_general_ci' */;
CREATE USER IF NOT EXISTS 'atlas'@'%' IDENTIFIED BY 'atlas';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `atlas`.* TO 'atlas'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
